# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd9dbaf5096eb945fd1d45d7fa351fc3570551af3f06042743b41e61832ad1f6e6cd103f2d66e5692ec2cb05675e0daf8af5e674edb2061140ca93caa8aab347

test:
  secret_key_base: 9642dca8c65fffef4eb9c0da8c04c4400e11f5f2f537db32345a371b82a1119d5737d506911e2c8a77b34805def218c28c3cbb621e0f1137e964ec6f1b03ca6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
